# Copy vs View

In [9]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
co = a.copy()
a[1]=10
print("var :",a)
print("copy :",co)

var : [ 1 10  3  4  5]
copy : [1 2 3 4 5]


In [7]:
x = np.array([2, 3, 4, 5, 6])
vi = x.view()
x[1]=20
print("x :",x)
print("view :",vi)

x : [ 2 20  4  5  6]
view : [ 2 20  4  5  6]


# Join Array

In [10]:
import numpy as np
var= np.array([1,2,3,4])
var1 = np.array([9,8,8,6])
ar = np.concatenate((var,var1))
print(ar)

[1 2 3 4 9 8 8 6]


In [14]:
vr= np.array([[1,2],[3,4]])
vr1 = np.array([[9,8],[8,6]])
ar_new = np.concatenate((vr,vr1),axis=1)
ar_n = np.concatenate((vr,vr1),axis=0)
print(vr)
print()
print(vr1)
print()
print(ar_new)
print()
print(ar_n)

[[1 2]
 [3 4]]

[[9 8]
 [8 6]]

[[1 2 9 8]
 [3 4 8 6]]

[[1 2]
 [3 4]
 [9 8]
 [8 6]]


In [15]:
var_1= np.array([1,2,3,4])
var_2 = np.array([9,8,8,6])
ar = np.stack((var,var1))
print(ar)

[[1 2 3 4]
 [9 8 8 6]]


In [17]:
var_1= np.array([1,2,3,4])
var_2 = np.array([9,8,8,6])
ar = np.hstack((var,var1))
print(ar)

[1 2 3 4 9 8 8 6]


In [18]:
var_1= np.array([1,2,3,4])
var_2 = np.array([9,8,8,6])
ar = np.vstack((var,var1))
print(ar)

[[1 2 3 4]
 [9 8 8 6]]


In [21]:
var_1= np.array([1,2,3,4])
var_2 = np.array([9,8,8,6])
ar = np.stack((var,var1), axis = 0)
ar1 = np.hstack((var,var1)) #row
ar2 = np.vstack((var,var1)) #coloums
ar3 = np.dstack((var,var1)) #height
print(ar)
print()
print(ar1)
print()
print(ar2)
print()
print(ar3)

[[1 2 3 4]
 [9 8 8 6]]

[1 2 3 4 9 8 8 6]

[[1 2 3 4]
 [9 8 8 6]]

[[[1 9]
  [2 8]
  [3 8]
  [4 6]]]


# split array

In [25]:
var3 = np.array([1,2,3,4,5,6])
print(var3)

ar3 = np.array_split(var3, 3)
print()
print(ar3)
print(type(ar3))
print(ar3[1])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[3 4]


In [27]:
var4 = np.array([[1,2],[3,4],[5,6]])
print(var3)

ar4 = np.array_split(var4, 3)
ar5 = np.array_split(var4, 3,axis=1)
print()
print(ar4)
print()
print(ar5)
print(type(ar4))


[1 2 3 4 5 6]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]
<class 'list'>


# search

In [3]:
import numpy as np
var5 = np.array([1,2,3,2,5,6,2,8,9])
x = np.where(var5 == 2)
print(x)

(array([1, 3, 6], dtype=int64),)


In [4]:
var6 = np.array([1,2,3,4,6,7,8])
x1 = np.searchsorted(var6 , 5)
print(x1)

4


# Sort

In [6]:
var7 = np.array([2,1,10,4,6,9,8])
x2 = np.sort(var7)
print(x2)

[ 1  2  4  6  8  9 10]


In [7]:
var8 = np.array(['e','d','c','f','b'])
x3 = np.sort(var8)
print(x3)

['b' 'c' 'd' 'e' 'f']


# Filter

In [10]:
var9 = np.array(["a","s","d","f"])
f = [True,False,False,True]
new_ar = var9[f]
print(new_ar)

['a' 'f']


In [11]:
var10 = np.array([1,2,3,4,5])
np.random.shuffle(var10)
print(var10)

[1 2 4 3 5]


In [16]:
var11 =  np.array([1,2,3,4,5,2,5,6,2,7])
x4 = np.unique(var11,return_index=True,return_counts=True)
print(x4)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 4, 7, 9], dtype=int64), array([1, 3, 1, 1, 2, 1, 1], dtype=int64))


In [17]:
var12 = np.array([1,2,3,4,5,6])
y = np.resize(var12,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


In [20]:
var13 = np.array([1,2,3,4,5,6])
y = np.resize(var13,(3,2))
print(y)
print("Flatten :",y.flatten())
print("Ravel :",np.ravel(y,order="A"))

[[1 2]
 [3 4]
 [5 6]]
Flatten : [1 2 3 4 5 6]
Ravel : [1 2 3 4 5 6]


# Insert

In [27]:
var14  = np.array([1,2,3,4,5])
print(var14)
#v = np.insert(var14,2,6)
a = np.append(var14,6.5)
print(a)

[1 2 3 4 5]
[1.  2.  3.  4.  5.  6.5]


In [28]:
var15 = np.array([[1,2,3],[1,2,3]])
print(var15)
#v1 = np.insert(var15,1,6,axis = 0)
b = np.append(var15,[[45,44,23]],axis=0)
print(b)

[[1 2 3]
 [1 2 3]]
[[ 1  2  3]
 [ 1  2  3]
 [45 44 23]]


# Delete

In [30]:
var16 =np.array([1,2,3,4,5])
d = np.delete(var16,2)
print(d)

[1 2 4 5]


# Matrix

In [34]:
var17 = np.matrix([[1,2],[1,2]])
var18 = np.matrix([[1,2],[1,2]])
print(var17)
print()
print(var18)
print()
print(var17.dot(var18))
print(type(var17))

[[1 2]
 [1 2]]

[[1 2]
 [1 2]]

[[3 6]
 [3 6]]
<class 'numpy.matrix'>


In [40]:
var19 = np.matrix([[1,2,3],[4,5,6]])
print(var19)
print()
print(np.transpose(var19))
print()
print(var19.T)
print()
print(np.swapaxes(var19,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [44]:
var20 = np.matrix([[1,2],[3,4]])
print(var20)
print()
print(np.swapaxes(var20,0,1))


[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [45]:
var21 = np.matrix([[1,2],[3,4]])
print(var21)
print()
print(np.linalg.inv(var21))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [48]:
var22 = np.matrix([[1,2],[3,4]])
print(var22)
print()
print(np.linalg.matrix_power(var22,2))
print()
print(np.linalg.matrix_power(var22,0))
print()
print(np.linalg.matrix_power(var22,-2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [52]:
var23 = np.matrix([[1,2,3],[3,4,3],[1,2,3]])
print(var23)
print()
print(np.linalg.det(var23))

[[1 2 3]
 [3 4 3]
 [1 2 3]]

0.0
